import KEY from '../../objects/keys';

export default {
    Map: [    
        KEY.INVALID,        KEY.ESCAPE,         KEY.F1,             KEY.F2,             KEY.F3,             KEY.F4,             KEY.F5,             KEY.F6,             KEY.F7,         KEY.F8, 
        KEY.F9,             KEY.F10,            KEY.F11,            KEY.TILDE,          KEY.ONE,            KEY.TWO,            KEY.THREE,          KEY.FOUR,           KEY.FIVE,       KEY.SIX, 
        KEY.SEVEN,          KEY.EIGHT,          KEY.NINE,           KEY.ZERO,           KEY.MINUS,          KEY.TAB,            KEY.Q,              KEY.W,              KEY.E,          KEY.R, 
        KEY.T,              KEY.Y,              KEY.U,              KEY.I,              KEY.O,              KEY.P,              KEY.OPEN_BRACKET,   KEY.CAPS_LOCK,      KEY.A,          KEY.S, 
        KEY.D,              KEY.F,              KEY.G,              KEY.H,              KEY.J,              KEY.K,              KEY.L,              KEY.SEMICOLON,      KEY.APOSTROPHE, KEY.LEFT_SHIFT,
        KEY.INVALID,        KEY.Z,              KEY.X,              KEY.C,              KEY.V,              KEY.B,              KEY.N,              KEY.M,              KEY.COMMA,      KEY.PERIOD,
        KEY.FORWARD_SLASH,  KEY.LEFT_CTRL,      KEY.LEFT_WIN,       KEY.LEFT_ALT,       KEY.INVALID,        KEY.SPACE,          KEY.INVALID,        KEY.INVALID,        KEY.RIGHT_ALT,  KEY.RIGHT_WIN,
        KEY.APP_SELECT,     KEY.LED_PROFILE,    KEY.LED_BRIGHTNESS, KEY.F12,            KEY.PRINT_SCREEN,   KEY.SCROLL_LOCK,    KEY.PAUSE_BREAK,    KEY.INSERT,         KEY.HOME,       KEY.PAGE_UP,
        KEY.CLOSE_BRACKET,  KEY.BACKSLASH,      KEY.INVALID,        KEY.ENTER,          KEY.INVALID,        KEY.EQUALS,         KEY.INVALID,        KEY.BACKSPACE,      KEY.DELETE,     KEY.END,
        KEY.PAGE_DOWN,      KEY.RIGHT_SHIFT,    KEY.RIGHT_CTRL,     KEY.ARROW_UP,       KEY.ARROW_LEFT,     KEY.ARROW_DOWN,     KEY.ARROW_RIGHT,    KEY.WIN_LOCK,       KEY.MUTE,       KEY.STOP,
        KEY.PREV,           KEY.PLAY,           KEY.NEXT,           KEY.NUM_LOCK,       KEY.NUM_SLASH,      KEY.NUM_ASTERISK,   KEY.NUM_MINUS,      KEY.NUM_PLUS,       KEY.NUM_ENTER,  KEY.NUM_7,
        KEY.NUM_8,          KEY.NUM_9,          KEY.INVALID,        KEY.NUM_4,          KEY.NUM_5,          KEY.NUM_6,          KEY.NUM_1,          KEY.NUM_2,          KEY.NUM_3,      KEY.NUM_0,
        KEY.NUM_DOT,        KEY.INVALID,        KEY.INVALID,        KEY.G1,             KEY.INVALID,        KEY.INVALID,        KEY.G2,             KEY.INVALID,        KEY.INVALID,    KEY.G3,
        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.G4,         KEY.INVALID,
        KEY.INVALID,        KEY.G5,             KEY.INVALID,        KEY.INVALID,        KEY.G6,             KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,    KEY.INVALID,
        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,    KEY.INVALID,
        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,        KEY.INVALID,    KEY.INVALID,
        KEY.BAR_1,          KEY.BAR_2,          KEY.BAR_3,          KEY.BAR_4,          KEY.BAR_5,          KEY.BAR_6,          KEY.BAR_7,          KEY.BAR_8,          KEY.BAR_9 ,     KEY.BAR_10,
        KEY.BAR_11,         KEY.BAR_12,         KEY.BAR_13,         KEY.BAR_14,         KEY.BAR_15,         KEY.BAR_16,         KEY.BAR_17,         KEY.BAR_18,         KEY.BAR_19,     KEY.INVALID
    ],
    VisualizerRows: [
        [ KEY.G6, KEY.G5, KEY.G4, KEY.G3, KEY.G2, KEY.G1, KEY.BAR_1],
        [ KEY.LEFT_CTRL, KEY.LEFT_SHIFT, KEY.CAPS_LOCK, KEY.TAB, KEY.TILDE, KEY.ESCAPE, KEY.BAR_2, KEY.INVALID, KEY.INVALID ],
        [ KEY.LEFT_WIN, KEY.Z, KEY.A, KEY.Q, KEY.ONE, KEY.F1, KEY.LED_PROFILE, KEY.BAR_3, KEY.INVALID, KEY.INVALID, KEY.INVALID  ],
        [ KEY.LEFT_ALT, KEY.X, KEY.S, KEY.W, KEY.TWO, KEY.F2, KEY.LED_BRIGHTNESS, KEY.BAR_4, KEY.INVALID ],
        [ KEY.INVALID, KEY.C, KEY.D, KEY.E, KEY.THREE, KEY.F3, KEY.WIN_LOCK, KEY.BAR_5 ],
        [ KEY.INVALID, KEY.V, KEY.F, KEY.R, KEY.FOUR, KEY.F4, KEY.BAR_6 ],
        [ KEY.SPACE, KEY.B, KEY.G, KEY.T, KEY.FIVE, ],
        [ KEY.N, KEY.H, KEY.Y, KEY.SIX, KEY.F5 ],
        [ KEY.M, KEY.J, KEY.U, KEY.SEVEN, KEY.F6, KEY.BAR_7 ],
        [ KEY.COMMA, KEY.K, KEY.I, KEY.EIGHT, KEY.F7, KEY.BAR_8 ],
        [ KEY.PERIOD, KEY.L, KEY.O, KEY.NINE, KEY.F8, KEY.BAR_9 ],
        [ KEY.RIGHT_ALT, KEY.PERIOD, KEY.L, KEY.O, KEY.NINE, KEY.F8, KEY.BAR_10 ],
        [ KEY.RIGHT_WIN, KEY.FORWARD_SLASH, KEY.SEMICOLON, KEY.P, KEY.ZERO, KEY.BAR_11 ],
        [ KEY.APP_SELECT, KEY.APOSTROPHE, KEY.OPEN_BRACKET, KEY.MINUS, KEY.F9, KEY.BAR_12 ],
        [ KEY.INVALID, KEY.INVALID, KEY.CLOSE_BRACKET, KEY.EQUALS, KEY.F10, KEY.BAR_13 ],
        [ KEY.RIGHT_CTRL, KEY.RIGHT_SHIFT, KEY.ENTER, KEY.BACKSLASH, KEY.BACKSPACE, KEY.F12, KEY.BAR_14 ],
    ],
    VisualizerRowColors: [    
        [ 255,   0,   0], 
        [ 225,  30,   0],
        [ 195,  60,   0],
        [ 165,  90,   0],
        [ 135, 120,   0],
        [ 105, 150,   0],
        [  75, 180,   0],
        [  45, 210,   0],
        [   0, 255,   0],
        [   0, 225,  30],
        [   0, 195,  60],
        [   0, 165,  90],
        [   0, 135, 120],
        [   0, 105, 150],
        [   0,  75, 180],
        [   0,  45, 210],
        [   0,   0, 255],
    ]
}